name: Run Cypress Tests in Docker

on:
  push:
    branches:
      - "*"
  pull_request:
    types: ['opened']

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Run Cypress tests
        uses: addnab/docker-run-action@v3
        with:
          image: cypress/browsers:node-20.8.0-chrome-118-ff-118-edge-118
          options: --entrypoint ''
          run: |
            npx cypress run --config-file cypress.config.js